config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges
  post 'actual_charge', to: 'charges#actual_charge'
  get 'create_source', to: 'charges#create_source'
  get 'accepted_charge', to: 'charges#accepted_charge'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  protect_from_forgery except: [:actual_charge]

  def new; end

  def create_source
    source = Stripe::Source.create(
      type: 'alipay',
      amount: '5000',
      currency: 'aud',
      redirect: {
        # where to go after charge is accepted by customer
        return_url: "#{request.base_url}/accepted_charge"
      }
    )
    # stripe generated qr code for customer to scan
    redirect_to source[:redirect][:url]
  end

  def accepted_charge; end

  def actual_charge
    source = params.dig(:data, :object, :id)

    charge = Stripe::Charge.create(
      amount: 5000,
      currency: 'aud',
      source: source
    )
  rescue StandardError => e
    # Some error; display an error message.
    Rails.logger.info(e.message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/accepted_charge.html.erb
<h1> Charge accepted by customer and redirected from Stripe to here </h1>

app/views/charges/actual_charge.html.erb
<h1> This endpoint is for webhooks </h1>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= link_to "Pay Me $50", create_source_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  <body>
    <%= yield %>
  </body>
</html>